-- =============================================================================
-- DEAL_INTEL: Post-Deployment Grants
-- File: sql/08_post_deploy_grants.sql
-- Description: RBAC grants and caller privileges applied after all objects exist.
-- Run as: DEAL_INTEL_ADMIN (owns the database)
-- =============================================================================

USE ROLE DEAL_INTEL_ADMIN;
USE WAREHOUSE DEAL_INTEL_QUERY_WH;

-- =============================================================================
-- SECTION 1: Caller Privileges for SPCS Restricted Caller's Rights
-- DEAL_INTEL_ADMIN owns the SPCS service. These grants allow it to access
-- objects on behalf of the logged-in user.
-- =============================================================================

-- Database-level
GRANT ALL CALLER PRIVILEGES ON DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;

-- Schema-level
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL SCHEMAS IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;

-- Table/view/DT-level
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL TABLES IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL VIEWS IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL DYNAMIC TABLES IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;

-- Stages (presigned URL access for document retrieval)
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL STAGES IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;

-- Procedures
GRANT INHERITED CALLER USAGE ON ALL PROCEDURES IN DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_ADMIN;

-- Warehouse (app queries)
GRANT CALLER USAGE ON WAREHOUSE DEAL_INTEL_QUERY_WH TO ROLE DEAL_INTEL_ADMIN;

-- Cortex AI functions
GRANT CALLER USE AI FUNCTIONS ON ACCOUNT TO ROLE DEAL_INTEL_ADMIN;

-- Agent caller usage
GRANT CALLER USAGE ON AGENT DEAL_INTEL.SERVICES.DEAL_INTELLIGENCE_AGENT TO ROLE DEAL_INTEL_ADMIN;

-- Semantic View caller usage (required for agent's analyst tool)
GRANT ALL CALLER PRIVILEGES ON SEMANTIC VIEW DEAL_INTEL.SERVICES.DEAL_ANALYTICS_SV TO ROLE DEAL_INTEL_ADMIN;

-- Cortex Search caller usage
GRANT CALLER USAGE ON CORTEX SEARCH SERVICE DEAL_INTEL.SERVICES.DEAL_SEARCH_SVC TO ROLE DEAL_INTEL_ADMIN;
GRANT CALLER USAGE ON CORTEX SEARCH SERVICE DEAL_INTEL.SERVICES.DEAL_PAGE_SEARCH_SVC TO ROLE DEAL_INTEL_ADMIN;

-- SNOWFLAKE database (needed for Cortex AI functions from SPCS RCR context)
-- NOTE: Schema-level grants do NOT cover objects within schemas in RCR executables.
-- The FUNCTIONS grant is required for AI_CLASSIFY, AI_EXTRACT, PARSE_DOCUMENT, etc.
GRANT ALL CALLER PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DEAL_INTEL_ADMIN;
GRANT ALL INHERITED CALLER PRIVILEGES ON ALL SCHEMAS IN DATABASE SNOWFLAKE TO ROLE DEAL_INTEL_ADMIN;
GRANT INHERITED CALLER USAGE ON ALL FUNCTIONS IN DATABASE SNOWFLAKE TO ROLE DEAL_INTEL_ADMIN;

-- =============================================================================
-- SECTION 2: Standard RBAC Object Grants
-- DEAL_INTEL_ADMIN owns everything, grants to child roles.
-- =============================================================================

-- Database and schema USAGE
GRANT USAGE ON DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON DATABASE DEAL_INTEL TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON SCHEMA DEAL_INTEL.SERVICES TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON SCHEMA DEAL_INTEL.SERVICES TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON SCHEMA DEAL_INTEL.TELEMETRY TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON SCHEMA DEAL_INTEL.TELEMETRY TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON SCHEMA DEAL_INTEL.ADMIN TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON SCHEMA DEAL_INTEL.ADMIN TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON SCHEMA DEAL_INTEL.APP TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON SCHEMA DEAL_INTEL.APP_SERVICE TO ROLE DEAL_INTEL_USER;

-- Warehouse USAGE
GRANT USAGE ON WAREHOUSE DEAL_INTEL_QUERY_WH TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON WAREHOUSE DEAL_INTEL_QUERY_WH TO ROLE DEAL_INTEL_PIPELINE;
GRANT USAGE ON WAREHOUSE DEAL_INTEL_WH TO ROLE DEAL_INTEL_PIPELINE;

-- DATA schema — read for users, full for pipeline
GRANT SELECT ON ALL TABLES IN SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_USER;
GRANT ALL ON ALL TABLES IN SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_PIPELINE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_USER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEAL_INTEL.DATA TO ROLE DEAL_INTEL_USER;

-- SERVICES schema — search, agent, semantic view
GRANT USAGE ON ALL CORTEX SEARCH SERVICES IN SCHEMA DEAL_INTEL.SERVICES TO ROLE DEAL_INTEL_USER;
GRANT USAGE ON AGENT DEAL_INTEL.SERVICES.DEAL_INTELLIGENCE_AGENT TO ROLE DEAL_INTEL_USER;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW DEAL_INTEL.SERVICES.DEAL_ANALYTICS_SV TO ROLE DEAL_INTEL_USER;

-- TELEMETRY schema — read for users, write for pipeline
GRANT SELECT ON ALL TABLES IN SCHEMA DEAL_INTEL.TELEMETRY TO ROLE DEAL_INTEL_USER;
GRANT ALL ON ALL TABLES IN SCHEMA DEAL_INTEL.TELEMETRY TO ROLE DEAL_INTEL_PIPELINE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEAL_INTEL.TELEMETRY TO ROLE DEAL_INTEL_USER;

-- ADMIN schema — specific table grants for user-facing features
GRANT SELECT ON ALL TABLES IN SCHEMA DEAL_INTEL.ADMIN TO ROLE DEAL_INTEL_USER;
GRANT ALL ON ALL TABLES IN SCHEMA DEAL_INTEL.ADMIN TO ROLE DEAL_INTEL_PIPELINE;
GRANT INSERT, SELECT, DELETE ON DEAL_INTEL.ADMIN.DOCUMENT_BOOKMARKS TO ROLE DEAL_INTEL_USER;
GRANT INSERT, SELECT ON DEAL_INTEL.ADMIN.SEARCH_FEEDBACK TO ROLE DEAL_INTEL_USER;
GRANT INSERT, SELECT ON DEAL_INTEL.ADMIN.EXTRACTION_OVERRIDES TO ROLE DEAL_INTEL_USER;
GRANT INSERT, SELECT, UPDATE, DELETE ON DEAL_INTEL.ADMIN.SAVED_SEARCHES TO ROLE DEAL_INTEL_USER;
GRANT INSERT, SELECT ON DEAL_INTEL.TELEMETRY.AGENT_AUDIT_LOG TO ROLE DEAL_INTEL_USER;

-- Stage read access for pipeline
GRANT READ ON STAGE DEAL_INTEL.DATA.DEAL_DOCUMENTS_STAGE TO ROLE DEAL_INTEL_PIPELINE;
GRANT READ ON STAGE DEAL_INTEL.DATA.SAMPLE_STAGE TO ROLE DEAL_INTEL_PIPELINE;
GRANT READ ON STAGE DEAL_INTEL.DATA.METADATA_STAGE TO ROLE DEAL_INTEL_PIPELINE;

-- Cortex AI
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEAL_INTEL_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DEAL_INTEL_PIPELINE;

-- =============================================================================
-- SECTION 3: Role Hierarchy (idempotent)
-- =============================================================================

GRANT ROLE DEAL_INTEL_USER     TO ROLE DEAL_INTEL_ADMIN;
-- NOTE: DEAL_INTEL_PIPELINE must NOT be granted to DEAL_INTEL_ADMIN (RAP bypass issue)
-- GRANT ROLE DEAL_INTEL_PIPELINE TO ROLE DEAL_INTEL_ADMIN;

-- =============================================================================
-- SECTION 4: Verification
-- =============================================================================

SHOW CALLER GRANTS ON DATABASE DEAL_INTEL;

SELECT 'Post-deploy grants completed' AS status,
       CURRENT_TIMESTAMP() AS applied_at,
       CURRENT_ROLE() AS applied_by;
